// Code generated by the FlatBuffers compiler. DO NOT EDIT.
//
// Vendored from github.com/teslamotors/fleet-telemetry/messages/tesla
// to avoid pulling fleet-telemetry's heavy transitive dependencies
// (Kafka, GCP Pub/Sub, ZeroMQ, etc.).

package tesla

// Message is the union type discriminator for the FlatbuffersEnvelope message field.
type Message = byte

const (
	MessageNONE              Message = 0
	MessageFlatbuffersStream Message = 4
)

// EnumNamesMessage maps message type constants to human-readable names.
var EnumNamesMessage = map[Message]string{
	MessageNONE:              "NONE",
	MessageFlatbuffersStream: "FlatbuffersStream",
}
